version: "1"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0